# Generated by Django 4.1.5 on 2023-02-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_serial_number', models.CharField(max_length=255, unique=True)),
                ('machine_type', models.CharField(max_length=255)),
                ('machine_installation_year', models.CharField(max_length=255)),
                ('machine_intervention', models.CharField(max_length=255)),
                ('machine_option_list', models.CharField(max_length=255)),
                ('machine_slug', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MachineOptionList',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('EU_US', models.CharField(max_length=255)),
                ('length_x', models.CharField(max_length=255)),
                ('head_list', models.CharField(max_length=255)),
                ('table', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('machine_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_type_name', models.CharField(max_length=255)),
            ],
        ),
    ]
