# Generated by Django 4.1.5 on 2023-02-10 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCase',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=255)),
                ('case_created_by', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('problem_description', models.TextField()),
                ('technician_assigned_id', models.CharField(max_length=255)),
                ('time_case_create', models.TimeField(auto_now_add=True)),
                ('time_case_edited', models.TimeField(auto_now=True)),
                ('machine', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='machine.machine')),
            ],
        ),
    ]
